### ISSUE TITLE
Can I use these modules in image classification

### ISSUE THREAD

**Issue by guosusu** [jiayuzhou/MALSAR#14]
I want to use multi-task module to implement image classification. However, after reading your manual, I find that your data is not images. So I want to know can I use these modules in image classification? How can I do it? @jiayuzhou 
Thanks!

**Comment by jiayuzhou** [comment]
Converting image to vectors (though rearranging raw pixels or representation learning) can make your data fit the linear models used in this package. BTW, please do not use this issue function for this purpose since it is not an issue of the software package, but rather a modeling problem specific to your application.
