### ISSUE TITLE
what is the algorithm of the the least lasso demo

### ISSUE THREAD

**Issue by tangtangsiqi** [jiayuzhou/MALSAR#8]
in the least lasso demo，waht resolution is used？ is there a paper so that i can know more detailed information about the solution of lasso problem?

**Comment by jiayuzhou** [comment]
This question is not a software issue and should be discussed in Github issues.  

To answer your question: Because that l1 norm is separable, this problem is equivalently to solving a set of lasso problems, one for each task. The only thing that is shared among tasks is the regularization parameter. There are no paper talking about this joint formulation and it is not commonly used.
